### ISSUE TITLE
Improve the tsdoc about the accordion widget, change the `accordion collapse` expression to make it more easily understandable

### ISSUE THREAD

**Issue by divdavem** [AmadeusITGroup/AgnosUI#160]
Especially, the tsdoc currently mentions the [accordion collapse](https://github.com/AmadeusITGroup/AgnosUI/blob/v0.1.1/core/src/components/accordion/accordion.ts#L120) as a DOM element in the structure (and repeated several times in the doc).
As suggested by @ExFlo, maybe it should be called accordion body instead?

**Comment by ValentinNelu** [comment]
It was done like that to reflect the HTML structure in Bootstrap, should we abandon Bootstrap notation?

**Comment by divdavem** [comment]
> It was done like that to reflect the HTML structure in Bootstrap, should we abandon Bootstrap notation?

This issue is just about the tsdoc documentation to make it easier to understand, it is not meant to change the markup, for which we still follow Bootstrap.

**Comment by divdavem** [comment]
I think this issue is still relevant. The tsdoc of the core should be easily understandable without assuming that we always use Bootstrap (it should be CSS framework agnostic). Especially, the `accordion collapse` expression should be replaced or better explained.

**Comment by ValentinNelu** [comment]
@divdavem Hi I made this small PR about it: https://github.com/AmadeusITGroup/AgnosUI/pull/518 what do you think?
