### ISSUE TITLE
Demo: adapt the iframes height of the samples

### ISSUE THREAD

**Issue by fbasso** [AmadeusITGroup/AgnosUI#17]
The idea is to adapt the height of the iframe each time the inner content change

**Comment by quentinderoubaix** [comment]
Made a PR that uses a ResizeObserver for dynamic content.
Though it does not work super well with modals, due to the body elements being smaller than the modal backdrop...

**Comment by quentinderoubaix** [comment]
Closing as ResizeObserver is working as expected.
