### ISSUE TITLE
slider : the disabled attribute shouldn't be used on div elements

### ISSUE THREAD

**Issue by fbasso** [AmadeusITGroup/AgnosUI#212]
`disabled ` is not a valid attribute for a div. There is a warning in the Svelte markup.

Instead, the class `disabled ` should be used as it's done in Bootstrap for example for the [pagination](https://getbootstrap.com/docs/5.3/components/pagination/#disabled-and-active-states), or for the [links](https://getbootstrap.com/docs/5.3/components/buttons/#link-functionality-caveat).

**Comment by divdavem** [comment]
This was fixed in #218
