### ISSUE TITLE
Slider: className is not applied to the main container

### ISSUE THREAD

**Issue by fbasso** [AmadeusITGroup/AgnosUI#214]
In Angular, this input is not used. The class should be applied in the host.

```typescript
	/**
	 * CSS classes to be applied on the widget main container
	 */
	@Input('auClassName') className: string | undefined;
```

**Comment by MarkoOleksiyenko** [comment]
Fixed with https://github.com/AmadeusITGroup/AgnosUI/commit/a5454302440b057b3155a941faf23a53cdea3c0b
