### ISSUE TITLE
Unable to render server side components with slots (Svelte)

### ISSUE THREAD

**Issue by fbasso** [AmadeusITGroup/AgnosUI#28]
**Describe the bug**
Components with slot don't work with SSR (svelte)

**To Reproduce**
Add a `<Alert>` in a demo page

**Comment by divdavem** [comment]
I have opened the following issue on Svelte to fix part of the problem: https://github.com/sveltejs/svelte/issues/9137

**Comment by divdavem** [comment]
This issue was fixed in #592.
