### ISSUE TITLE
Angular widgets apis refactor

### ISSUE THREAD

**Issue by quentinderoubaix** [AmadeusITGroup/AgnosUI#47]
**Context**
Following our discussion regarding the angular widgets apis, we have decided that angular widgets should obey the following rules:
* the selector should not be **'au-$name'** but **'$htmlElement au$Name'**
* every input and output should prefixed with au

**Example of change**
For the rating default, this would mean going from:
```html
<au-rating [(rating)]="rating" (hover)="hovered = $event" (leave)="left = $event" ariaLabel="rating" />
```
to
```html
<div [(au-rating)]="rating" (au-hover)="hovered = $event" (au-leave)="left = $event" au-aria-label="rating"></div>
```

**Comment by divdavem** [comment]
As discussed today with @quentinderoubaix, maybe we should rather finally use camelCase:

```html
<div [(auRating)]="rating" (auHover)="hovered = $event" (auLeave)="left = $event" auAriaLabel="rating"></div>
```

That's what people are used to for attributes in Angular, and also otherwise, it is strange to have a mix of kebab-case and camelCase for bindings (i.e. `au-ratingChange`).
