### ISSUE TITLE
Relative imports with .js extension in our published packages (so that code can run unmodified in node.js with ESM)

### ISSUE THREAD

**Issue by divdavem** [AmadeusITGroup/AgnosUI#481]
It would be good to support running the code of our packages unmodified in node.js [with ESM](https://nodejs.org/api/esm.html).

This is needed especially for the server-side rendering (SSR) use case.

For this to work, as mentioned in [the Svelte packager documentation](https://kit.svelte.dev/docs/packaging#caveats):

> All relative file imports need to be fully specified, adhering to Node's ESM algorithm. This means that for a file like src/lib/something/index.js, you must include the filename with the extension:
> ```diff
> - import { something } from './something';
> + import { something } from './something/index.js';
> ```
> If you are using TypeScript, you need to import .ts files the same way, but using a .js file ending, not a .ts file ending. (This is a TypeScript design decision outside our control.) Setting "moduleResolution": "NodeNext" in your tsconfig.json or jsconfig.json will help you with this.

A first attempt to implement this was done in #150. The PR had some issues and is now closed, and much code was changed in the mean time.

**Comment by quentinderoubaix** [comment]
Was handled by building the core in common js and esm.
