### ISSUE TITLE
Make our Angular components use signal inputs, models and signal queries

### ISSUE THREAD

**Issue by quentinderoubaix** [AmadeusITGroup/AgnosUI#502]
**Description**
We have migrated to Angular 17.2, allowing us to start using even more signals into our widgets.

References:
https://next.angular.io/api/core/input
https://angular.io/api/core/model
https://angular.io/api/core/viewChild

Can be split into two parts:
- [x] #770
- [x] once they are not experimental any longer, migrate the bootstrap components

**Comment by mrednic-1A** [comment]
Here is an example with the Progressbar component migrated #566
