### ISSUE TITLE
[Slider] Accessibility dark theme for disabled elements

### ISSUE THREAD

**Issue by andreascorti** [AmadeusITGroup/AgnosUI#503]
**Describe the bug**
There is not enough contrast in dark mode for disabled items.
![image](https://github.com/AmadeusITGroup/AgnosUI/assets/2025573/2142e45a-edc3-44c8-bba3-f450a6c4260a)

**Comment by ExFlo** [comment]
disabled items should be flag as disabled with the correct aria attribute and then I think are not taken into account for contrast.

**Comment by andreascorti** [comment]
Closed because as correctly said by @ExFlo, disabled item are not subject of contrast rules.
