### ISSUE TITLE
Bootstrap fullscreen modal

### ISSUE THREAD

**Issue by divdavem** [AmadeusITGroup/AgnosUI#551]
As described in [bootstrap documentation](https://getbootstrap.com/docs/5.3/components/modal/#fullscreen-modal), in order to make a modal full-screen, it is necessary to add the `modal-fullscreen` class on the `modal-dialog` element.
However, there is currently no way to add a class on that specific element, cf the [corresponding line in the Svelte template](https://github.com/AmadeusITGroup/AgnosUI/blob/aa916094c437bcc161e9c3dfea38a215b06f0583/svelte/lib/src/components/modal/Modal.svelte#L58) (it is the same with other frameworks).

**Comment by ExFlo** [comment]
Should we start a new way of customizing the class inside our templates ? or just fix this single issue...

**Comment by andreascorti** [comment]
shouldn't be just a prop in this specific case for a bootstrap component?
